# -*- coding: utf-8 -*-
"""🪄 Module 04 discussion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBo6jbjuivehWrh7b73Bfv_iU_W0Ps5s
"""

import pandas as pd

df = pd.read_excel("data/rcel M4.xlsx")

df_2024 = df[df["year"] == 2024]

import os
st.write("Files in app directory:", os.listdir())
import matplotlib.pyplot as plt

apps = df_2024["app"]
left = [0] * len(df_2024)

fig, ax = plt.subplots(figsize=(8, 4))

for col, color in zip(
    ["almost_constant", "several_times_day", "once_day"],
    ["#1f4e79", "#4f81bd", "#9dc3e6"]
):
    ax.barh(apps, df_2024[col], left=left, color=color, label=col)
    left = left + df_2024[col]

ax.invert_yaxis()
ax.legend()
plt.show()

year = st.slider("Select year", 2022, 2023, 2024,2025)
df_year = df[df["year"] == year]
